version: "3"

services:
  database:
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./storage/mysql:/var/lib/mysql
